[tool.typos]
default.extend-ignore-words-re=[
        "^[a-zA-Z]{1,3}$", #to exclude typos in 3 letter words
]
files.ignore-hidden = false

[tool.ruff]
lint.ignore = [
    "F401", #imported but unused
]
show-fixes = true

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

[tool.tox]
env_list = ["3.8", "3.10", "3.12"]
